### PR TITLE
Update Xeexe.py

### PR DESCRIPTION
**Pull request by ferdinandlb**
I have refactored the code in two classes: "ConsoleManager" for the colored stuff and "Xeexe" for the Application.
I also added the LEFT-TO-RIGHT OVERRIDE character feature (gpj.exe => exe.jpg). 

Sorry for my English (i'm from Germany)...  :)

### CODE REVIEW

**Comment by apisiylo** [comment]
> I have refactored the code in two classes: "ConsoleManager" for the colored stuff and "Xeexe" for the Application.
> I also added the LEFT-TO-RIGHT OVERRIDE character feature (gpj.exe => exe.jpg).
> 
> Sorry for my English (i'm from Germany)... :)

Please i'm interested on how to bypass all antivirus with my trojan, please help me upload a video on how to use this "Update Xeexe.py"
Thanks

**Comment by ferdinandkedef** [comment]
> > I have refactored the code in two classes: "ConsoleManager" for the colored stuff and "Xeexe" for the Application.
> > I also added the LEFT-TO-RIGHT OVERRIDE character feature (gpj.exe => exe.jpg).
> > 
> > Sorry for my English (i'm from Germany)... :)
> 
> Please i'm interested on how to bypass all antivirus with my trojan, please help me upload a video on how to use this "Update Xeexe.py"
> Thanks

This is actually an Update for the owner of this Repository...

**Comment by apisiylo** [comment]
Please share us a video tutorial on how to use this tools pls

**Comment by apisiylo** [comment]
Skype: apisiylo 

Pls add me up on Skype we can talk about personal business.
I'm very much concerned about bypassing all antivirus including windows defender.

Please contact me !

Thanks

**Review by persianhydra — COMMENTED** [review]
thanks but it just reverse name not spoofing extension

**Pull request closed without merging**
